[workspace]
publish = false
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = true
release_always = false

changelog_update = true
changelog_path = "./CHANGELOG.md"

[[package]]
name = "wadtools"
release = true
publish = false
